#!/bin/bash
# build_asm.sh - Build assembly files and C++ tools for MP/M II Emulator
# Part of MP/M II Emulator
# SPDX-License-Identifier: GPL-3.0-or-later
#
# ==============================================================================
# BOOT PROCESS OVERVIEW
# ==============================================================================
#
# When MP/M II boots, there are THREE layers of BIOS, each with its own
# disk parameters (DPB). If ANY layer has the wrong DPB for your disk format,
# the boot will fail.
#
# Layer 1: LDRBIOS (Loader BIOS)
#   - Used by: MPMLDR.COM (the loader)
#   - Purpose: Read MPM.SYS from disk into memory
#   - Location: 0x1700 in boot image
#   - File: ldrbios.bin (one LDRBIOS for all formats)
#   - Emulator's port dispatch handles actual disk format
#
# Layer 2: BNKXIOS (Banked XIOS)
#   - Used by: MP/M II kernel after boot
#   - Purpose: All disk/console I/O during normal operation
#   - Format: SPR file (relocatable)
#   - File: BNKXIOS.SPR
#   - Built into MPM.SYS by GENSYS
#
# Layer 3: RESXIOS (Resident XIOS)
#   - Used by: Resident portion of MP/M II
#   - Purpose: Minimal I/O when banked code is swapped out
#   - Format: SPR file (relocatable)
#   - Note: We use BNKXIOS for both (no separate RESXIOS needed for emulator)
#
# ==============================================================================
# DISK FORMAT: hd1k (8MB)
# ==============================================================================
#
# Physical geometry:
#   - 1024 tracks
#   - 16 sectors per track
#   - 512 bytes per sector
#   - Total: 8,388,608 bytes (8MB)
#
# CP/M logical view (128-byte records):
#   - SPT = 64 (16 sectors * 512 bytes / 128 = 64 logical sectors per track)
#   - BSH = 5, BLM = 31 (4KB allocation blocks)
#   - DSM = 2039 (2040 blocks)
#   - DRM = 1023 (1024 directory entries)
#   - OFF = 2 (2 reserved/system tracks)
#   - No sector skew (skew = 0)
#
# Directory starts at track 2 (after OFF=2 system tracks)
#
# ==============================================================================
# BUILD TOOLS
# ==============================================================================
#
# Assembly (native, M80/L80 compatible):
#   - um80: Native MACRO-80 compatible assembler (.asm -> .rel)
#   - ul80: Native LINK-80 compatible linker (.rel -> .com, .hex, or .prl)
#
# C++ tools (built by cmake):
#   - mkboot: Creates boot image from LDRBIOS + MPMLDR
#
# CP/M tools:
#   - GENSYS.COM: Generates MPM.SYS from component SPR files
#   - cpmtools: Native tools for manipulating CP/M disk images
#
# ==============================================================================
# FILES AND THEIR PURPOSES
# ==============================================================================
#
# Source files (asm/):
#   coldboot.asm       - Cold start loader (sector 0, loads MPMLDR+LDRBIOS)
#   ldrbios.asm        - LDRBIOS for loader phase (loads at 0x1700)
#   bnkxios.asm        - BNKXIOS using I/O port traps to emulator
#
# Binary outputs (asm/):
#   coldboot.bin       - Cold start loader (512 bytes, sector 0)
#   ldrbios.bin        - Assembled LDRBIOS (loads at 0x1700)
#   BNKXIOS.SPR        - BNKXIOS as relocatable SPR file
#
# Boot images (disks/):
#   mpm2boot_<format>.bin - Boot image (LDRBIOS + MPMLDR)
#
# System files (on disk image):
#   MPM.SYS            - Generated by GENSYS, contains linked system
#   MPMLDR.COM         - Loader program (serial must match RESBDOS)
#
# ==============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
ASM_DIR="$PROJECT_DIR/asm"
BUILD_DIR="$PROJECT_DIR/build"
DISKS_DIR="$PROJECT_DIR/disks"
CPMEMU="${CPMEMU:-$HOME/src/cpmemu/src/cpmemu}"

# Disk format to build for
DISK_FORMAT="${1:-hd1k}"

echo "=============================================="
echo "MP/M II Assembly and Tools Build"
echo "=============================================="
echo "Disk format: $DISK_FORMAT"
echo ""

# ------------------------------------------------------------------------------
# Step 1: Build C++ emulator and tools
# ------------------------------------------------------------------------------
echo "Step 1: Building C++ emulator and tools..."
cd "$BUILD_DIR"
cmake .. > /dev/null
make -j4 2>&1 | grep -v "^make\[" || true
echo "  Built: mpm2_emu, mkboot"
echo ""

# ------------------------------------------------------------------------------
# Step 2: Assemble LDRBIOS for the target disk format
# ------------------------------------------------------------------------------
echo "Step 2: Assembling LDRBIOS for $DISK_FORMAT..."
cd "$ASM_DIR"

rm -f *.rel *.spr *.SPR 

# Only one LDRBIOS - the SSSD floppy version
# The emulator's port dispatch handles actual disk I/O regardless of format
LDRBIOS="ldrbios"
um80 -o "${LDRBIOS}.rel" "${LDRBIOS}.asm"
# LDRBIOS loads at 0x1700, so link with that origin
ul80 -p 1700 -o "${LDRBIOS}.bin" "${LDRBIOS}.rel"

# Create stripped version for boot area (skip 0x1700 bytes of ORG padding)
dd if="${LDRBIOS}.bin" of="${LDRBIOS}_boot.bin" bs=1 skip=$((0x1700)) 2>/dev/null
LDRBIOS_CODE_SIZE=$(stat -f%z "${LDRBIOS}_boot.bin")
echo "  Output: $ASM_DIR/${LDRBIOS}.bin (with ORG padding)"
echo "  Output: $ASM_DIR/${LDRBIOS}_boot.bin ($LDRBIOS_CODE_SIZE bytes, for boot area at 0x1700)"
echo ""

# ------------------------------------------------------------------------------
# Step 3: Assemble cold boot loader
# ------------------------------------------------------------------------------
echo "Step 3: Assembling cold boot loader..."
cd "$ASM_DIR"

COLDBOOT="coldboot"
um80 -o "${COLDBOOT}.rel" "${COLDBOOT}.asm"
# Cold boot loader runs at 0x0000 (loaded from sector 0)
ul80 -p 0 -o "${COLDBOOT}.bin" "${COLDBOOT}.rel"

# Pad to exactly 512 bytes (one physical sector)
COLDBOOT_SIZE=$(stat -f%z "${COLDBOOT}.bin")
if [ "$COLDBOOT_SIZE" -lt 512 ]; then
    dd if=/dev/zero bs=1 count=$((512 - COLDBOOT_SIZE)) >> "${COLDBOOT}.bin" 2>/dev/null
    echo "  Padded ${COLDBOOT}.bin to 512 bytes"
elif [ "$COLDBOOT_SIZE" -gt 512 ]; then
    echo "  ERROR: ${COLDBOOT}.bin is $COLDBOOT_SIZE bytes (max 512)"
    exit 1
fi

echo "  Output: $ASM_DIR/${COLDBOOT}.bin (512 bytes)"
echo ""

# ------------------------------------------------------------------------------
# Step 4: Assemble BNKXIOS
# ------------------------------------------------------------------------------
echo "Step 4: Assembling BNKXIOS..."
cd "$ASM_DIR"

BNKXIOS="bnkxios"
um80 -o "${BNKXIOS}.rel" "${BNKXIOS}.asm"
ul80 --prl -p 0 -o "${BNKXIOS}.spr" "${BNKXIOS}.rel"

echo "  Output: $ASM_DIR/${BNKXIOS}.spr"
echo ""

# ------------------------------------------------------------------------------
# Step 5: Create boot image
# ------------------------------------------------------------------------------
echo "Step 5: Creating boot image..."
cd "$PROJECT_DIR"

# We need:
# - LDRBIOS binary (for disk I/O during load)
# - MPMLDR.COM (the loader program)
# The boot image places LDRBIOS at 0x1700 and MPMLDR at 0x0100

MPMLDR="$PROJECT_DIR/mpm2_external/mpm2dist/MPMLDR.COM"
if [ ! -f "$MPMLDR" ]; then
    # Try to extract from disk image
    MPMLDR="$DISKS_DIR/mpmldr.com"
    if [ ! -f "$MPMLDR" ]; then
        echo "  Extracting MPMLDR.COM from disk..."
        cpmcp -T raw -f wbw_hd1k "$DISKS_DIR/mpm2_hd1k.img" "0:mpmldr.com" "$MPMLDR" 2>/dev/null || true
    fi
fi

# Boot image name based on disk format
BOOT_IMAGE="$DISKS_DIR/mpm2boot_${DISK_FORMAT}.bin"

"$BUILD_DIR/mkboot" \
    -l "$ASM_DIR/${LDRBIOS}.bin" \
    -m "$MPMLDR" \
    -o "$BOOT_IMAGE"

echo "  Output: $BOOT_IMAGE"
echo ""

# Verify boot image has LDRBIOS at correct address
echo "  Verifying boot image LDRBIOS..."
# Check for LDRBIOS signature at 0x1700 (should start with JP instruction C3)
LDRBIOS_START=$(xxd -s 0x1700 -l 1 "$BOOT_IMAGE" | awk '{print $2}')
if [ "$LDRBIOS_START" = "c3" ]; then
    echo "  LDRBIOS at 0x1700 - OK (starts with JP)"
else
    echo "  WARNING: LDRBIOS may not be at 0x1700 (got: $LDRBIOS_START)"
fi
echo ""

# ------------------------------------------------------------------------------
# Step 6: Write boot area to disk image
# ------------------------------------------------------------------------------
echo "Step 6: Writing boot area to disk..."

CPM_DISK="$PROJECT_DIR/../cpmemu/util/cpm_disk.py"
DISK_IMAGE="$DISKS_DIR/mpm2_hd1k.img"

if [ -f "$DISK_IMAGE" ] && [ -f "$CPM_DISK" ]; then
    # Boot area layout (512-byte physical sectors, 128-byte logical sectors):
    #   Physical sector 0 (logical 0-3):     coldboot.bin
    #   Physical sectors 1-12 (logical 4-51): MPMLDR.COM (~6KB)
    #   Physical sectors 13-16 (logical 52-67): LDRBIOS (~2KB)

    # Write cold boot loader to sector 0
    "$CPM_DISK" write-boot "$DISK_IMAGE" "$ASM_DIR/${COLDBOOT}.bin" 0 1

    # Write MPMLDR.COM to sectors 1-12
    if [ -f "$MPMLDR" ]; then
        "$CPM_DISK" write-boot "$DISK_IMAGE" "$MPMLDR" 1 12
    elif [ -f "$DISKS_DIR/mpmldr.com" ]; then
        "$CPM_DISK" write-boot "$DISK_IMAGE" "$DISKS_DIR/mpmldr.com" 1 12
    else
        echo "  WARNING: MPMLDR.COM not found, skipping"
    fi

    # Write LDRBIOS to sectors 13-16
    "$CPM_DISK" write-boot "$DISK_IMAGE" "$ASM_DIR/${LDRBIOS}_boot.bin" 13 4

    echo "  Boot area written to $DISK_IMAGE"
else
    if [ ! -f "$DISK_IMAGE" ]; then
        echo "  Disk image not found: $DISK_IMAGE"
        echo "  Run scripts/build_hd1k.sh first to create disk image"
    fi
    if [ ! -f "$CPM_DISK" ]; then
        echo "  cpm_disk.py not found: $CPM_DISK"
    fi
fi
echo ""

# ------------------------------------------------------------------------------
# Step 7: Summary
# ------------------------------------------------------------------------------
echo "=============================================="
echo "Assembly Build Complete"
echo "=============================================="
echo ""
echo "Files created:"
echo "  Cold boot:   $ASM_DIR/${COLDBOOT}.bin (512 bytes, sector 0)"
echo "  LDRBIOS:     $ASM_DIR/${LDRBIOS}_boot.bin (for boot area, sectors 13+)"
echo "  BNKXIOS:     $ASM_DIR/${BNKXIOS}.spr"
echo "  Boot image:  $BOOT_IMAGE (legacy)"
echo ""
if [ -f "$DISK_IMAGE" ]; then
    echo "Boot area written to: $DISK_IMAGE"
    echo ""
    echo "To run:"
    echo "  $BUILD_DIR/mpm2_emu -l -d A:$DISK_IMAGE"
else
    echo "Next steps (or run build_all.sh to do all):"
    echo "  1. scripts/build_hd1k.sh  - Create disk image"
    echo "  2. scripts/gensys.sh      - Generate MPM.SYS"
fi
echo ""
